apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-service-monitor.fullname" . }}-server
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ai-service-monitor.server.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.server.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
