apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-service-monitor.fullname" . }}-server
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ai-service-monitor.server.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.server.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
