apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: ai-monitor
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/part-of: ai-service-monitor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: server
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP
